version: "1"
services:
  myDB:
    image: lscr.io/linuxserver/mariadb:arm32v7-version-10.6.13-r0
    container_name : myDB
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=No88138Jun2011
    ports:
      - 5001:3306
    volumes:
      - ./mydata:/config
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    links:
      - myDB:db 
    ports:
      - 8080:80
    volumes:
      - ./phpApp:/var/www/html
    restart: unless-stopped
  